name: spotify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: 2.0.16  # Add the appropriate version
  flutter_bloc: ^8.1.6  # Add the appropriate version
  hydrated_bloc: ^9.1.5  # Add the appropriate version
  path_provider: ^2.0.8  # Add the appropriate version
  firebase_core: ^2.5.0  # Add the appropriate version
  firebase_auth: ^4.5.0  # Add the appropriate version
  get_it: ^7.2.0  # Add the appropriate version
  dartz: ^0.10.0  # Add the appropriate version
  cloud_firestore: ^4.5.0  # Add the appropriate version
  just_audio: ^0.9.10  # Add the appropriate version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
